name: FastAPI CI with Docker

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t fastapi-app .

    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 --name test-app fastapi-app
        sleep 5  # give the app time to start
        curl --fail http://localhost:8000 || exit 1
    - name: Run unit tests
      run: |
        docker run fastapi-app pytest
